FEATURE: Save system generated messages to the contact

Scenario: Contributions - Receipt (off-line)

WHEN "Contributions - Receipt (off-line)" is selected for the setting "Message Templates to create activities for when sent" on the settings page for this extension (`civicrm/swmactivities/settings`)
AND a backend (offline) contribution is created
AND the "Send Receipt?" checkbox is checked
AND the contact receives a receipt generated by the "Contributions - Receipt (off-line)" template
THEN an activity will be created for that contact with the text of the email in the details field.
